# .travis.yml
language: node_js

node_js:
  - '4'
  - '6'
  - '8'
  - 'node'
  - 'lts/*'

before_script:
  - mysql -uroot -e 'create database dbqueue_testing_db;'

services:
  - mysql

matrix:
  fast_finish: true
